jobs:
  ubuntu:
    name: Ubuntu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout master branch
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install drafter
      run: npm install drafter
    - continue-on-error: true
      name: Build
      run: node dev/parse.js
name: Check Apiary blueprint
on:
  repository_dispatch:
    types: trigger-ga___apiary.yml
