jobs:
  build:
    name: ${{ matrix.os }} with Java 17
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout master branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: oracle
        java-version: '17'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Checkout Universal ctags
      uses: actions/checkout@v4
      with:
        path: ctags
        repository: universal-ctags/ctags
    - continue-on-error: true
      if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Install pre-requisites (Unix)
      run: ./dev/before_install
    - continue-on-error: true
      if: runner.os == 'Windows'
      name: Install Universal ctags (Windows)
      run: choco install universal-ctags
    - continue-on-error: true
      if: runner.os == 'Linux' || runner.os == 'macOS'
      name: Before build actions (Unix)
      run: ./dev/before
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENGROK_PULL_REQUEST: ${{ github.head_ref }}
        OPENGROK_REF: ${{ github.ref }}
        OPENGROK_REPO_SLUG: ${{ github.repository }}
        OPENGROK_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Maven build
      run: ./dev/main
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
