jobs:
  build:
    needs: get_tag
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout master branch
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: oracle
        java-version: '17'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Checkout Universal ctags
      uses: actions/checkout@v4
      with:
        path: ctags
        repository: universal-ctags/ctags
    - continue-on-error: true
      name: Install pre-requisites
      run: ./dev/before_install
    - continue-on-error: true
      name: Before build actions
      run: ./dev/before
    - continue-on-error: true
      name: Build
      run: ./mvnw -DskipTests=true -Dmaven.javadoc.skip=false -B -V package
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      name: Create Release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release-asset
      name: Upload release tarball
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/octet-stream
        asset_name: opengrok-${{ needs.get_tag.outputs.tag }}.tar.gz
        asset_path: ./distribution/target/opengrok-${{ needs.get_tag.outputs.tag }}.tar.gz
        upload_url: ${{ steps.create_release.outputs.upload_url }}
  get_tag:
    name: Get tag name
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout master branch
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        OPENGROK_REF: ${{ github.ref }}
      id: get_tag
      name: Get the tag name
      run: ./dev/ref2tag.sh
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
